/**
 * Generate src/lib/embed/clientLogos.generated.ts from @lobehub/icons-static-svg.
 *
 * Embed cards are standalone SVG responses (CSP `default-src 'none'` and
 * GitHub's camo proxy both block external image fetches), so client logos must
 * be inlined as SVG markup. This script copies the icons the embed templates
 * need out of the icon package at development time so the runtime bundle has
 * no filesystem dependency on node_modules.
 *
 * Run with: bun scripts/generate-embed-logos.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const iconsDir = join(
  dirname(require.resolve("@lobehub/icons-static-svg/package.json")),
  "icons",
);
const outFile = join(here, "../src/lib/embed/clientLogos.generated.ts");

/**
 * ClientType -> @lobehub/icons-static-svg icon slug. Clients without a
 * matching lobehub icon are omitted and keep the colored-dot fallback.
 */
const CLIENT_ICON_SLUGS: Record<string, string> = {
  opencode: "opencode",
  claude: "claude-color",
  codex: "codex-color",
  copilot: "githubcopilot",
  gemini: "geminicli-color",
  cursor: "cursor",
  amp: "amp-color",
  openclaw: "openclaw-color",
  hermes: "hermesagent",
  pi: "pi",
  kimi: "kimi-color",
  qwen: "qwen-color",
  roocode: "roocode",
  kilocode: "kilocode",
  // `kilo` (nicepkg's CLI) is deliberately absent: it is a different project
  // from Kilo-Org's extension above and has no lobehub icon of its own, so it
  // takes the colored-dot fallback rather than wearing someone else's mark.
  kiro: "kiro-color",
  goose: "goose",
  antigravity: "antigravity-color",
  "antigravity-cli": "antigravity-color",
  trae: "trae-color",
  cline: "cline",
  grok: "grok",
  micode: "xiaomimimo",
  junie: "junie-color",
  zcode: "zai",
  opencodereview: "alibaba-color",
  codebuddy: "codebuddy-color",
  "devin-cli": "devin-color",
  "devin-desktop": "devin-color",
};

interface ParsedIcon {
  viewBox: string;
  /** Root <svg> presentation attributes worth preserving (fill, fill-rule, …). */
  rootAttrs: string;
  /** True when the icon is monochrome and expects a caller-supplied color. */
  mono: boolean;
  body: string;
}

const DROPPED_ROOT_ATTRS = new Set([
  "height",
  "width",
  "style",
  "xmlns",
  "viewBox",
  "class",
]);

function parseIcon(slug: string): ParsedIcon {
  const raw = readFileSync(join(iconsDir, `${slug}.svg`), "utf8");
  const rootMatch = raw.match(/^<svg\s([^>]*)>([\s\S]*)<\/svg>\s*$/);
  if (!rootMatch) throw new Error(`Unexpected SVG shape for ${slug}`);
  const [, rootAttrsRaw, bodyRaw] = rootMatch;

  const viewBoxMatch = rootAttrsRaw.match(/viewBox="([^"]+)"/);
  if (!viewBoxMatch) throw new Error(`Missing viewBox for ${slug}`);

  const keptAttrs: string[] = [];
  for (const attr of rootAttrsRaw.matchAll(/([a-zA-Z-]+)="([^"]*)"/g)) {
    if (!DROPPED_ROOT_ATTRS.has(attr[1])) keptAttrs.push(`${attr[1]}="${attr[2]}"`);
  }

  return {
    viewBox: viewBoxMatch[1],
    rootAttrs: keptAttrs.join(" "),
    mono: raw.includes("currentColor"),
    body: bodyRaw.replace(/<title>[^<]*<\/title>/, "").trim(),
  };
}

const entries = Object.entries(CLIENT_ICON_SLUGS).map(([client, slug]) => {
  const icon = parseIcon(slug);
  return `  ${JSON.stringify(client)}: {\n    viewBox: ${JSON.stringify(icon.viewBox)},\n    rootAttrs: ${JSON.stringify(icon.rootAttrs)},\n    mono: ${icon.mono},\n    body: ${JSON.stringify(icon.body)},\n  },`;
});

const output = `/**
 * AUTO-GENERATED by scripts/generate-embed-logos.ts — do not edit by hand.
 * Inlined client logos from @lobehub/icons-static-svg for the embed SVG cards.
 * Regenerate with: bun scripts/generate-embed-logos.ts
 */

export interface EmbedClientLogo {
  viewBox: string;
  /** Root <svg> presentation attributes (fill, fill-rule, …) from the source icon. */
  rootAttrs: string;
  /** Monochrome icon that expects a caller-supplied color via currentColor. */
  mono: boolean;
  body: string;
}

export const EMBED_CLIENT_LOGOS: Record<string, EmbedClientLogo> = {
${entries.join("\n")}
};
`;

writeFileSync(outFile, output);
console.log(
  `Wrote ${Object.keys(CLIENT_ICON_SLUGS).length} client logos to ${outFile}`,
);
