/**
 * Generate src/lib/og/fonts.generated.ts from Google Fonts.
 *
 * The share-card renderer (Satori) cannot use next/font and has no font of its
 * own beyond Noto Sans, so the faces the site uses are inlined as base64. That
 * keeps `/api/og` free of filesystem reads and outbound fetches, which matters
 * because the same route runs under standalone Node and under Workers.
 *
 * Only the `latin` subset is kept: Satori takes TTF/OTF/WOFF (not WOFF2), and
 * the card text is a name, a handle and figures.
 *
 * Run with: bun scripts/generate-og-fonts.ts
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outFile = join(here, "../src/lib/og/fonts.generated.ts");

const FACES = [
  { family: "Geist", query: "Geist", weight: 500 },
  { family: "Geist", query: "Geist", weight: 600 },
  { family: "JetBrains Mono", query: "JetBrains+Mono", weight: 600 },
] as const;

// An old WebKit UA makes the css2 API answer with WOFF rather than WOFF2.
const LEGACY_UA =
  "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/534.30 (KHTML, like Gecko) Safari/534.30";

async function latinWoffUrl(query: string, weight: number): Promise<string> {
  const res = await fetch(
    `https://fonts.googleapis.com/css2?family=${query}:wght@${weight}&display=swap`,
    { headers: { "User-Agent": LEGACY_UA } },
  );
  if (!res.ok) throw new Error(`css2 ${query}@${weight}: ${res.status}`);
  const css = await res.text();
  const block = css.split("/* latin */")[1];
  const url = block?.match(/src:\s*url\(([^)]+)\)\s*format\('woff'\)/)?.[1];
  if (!url) throw new Error(`no latin woff for ${query}@${weight}`);
  return url;
}

const entries: string[] = [];
for (const face of FACES) {
  const url = await latinWoffUrl(face.query, face.weight);
  const bytes = Buffer.from(await (await fetch(url)).arrayBuffer());
  console.log(`${face.family} ${face.weight}: ${bytes.length} bytes`);
  entries.push(
    `  { name: ${JSON.stringify(face.family)}, weight: ${face.weight}, data: ${JSON.stringify(bytes.toString("base64"))} },`,
  );
}

writeFileSync(
  outFile,
  `/**
 * AUTO-GENERATED by scripts/generate-og-fonts.ts — do not edit by hand.
 * Latin WOFF subsets of the site's faces, inlined for the Open Graph renderer.
 * Regenerate with: bun scripts/generate-og-fonts.ts
 */

export interface OgFontSource {
  name: string;
  weight: 500 | 600;
  /** Base64-encoded WOFF. */
  data: string;
}

export const OG_FONT_SOURCES: OgFontSource[] = [
${entries.join("\n")}
];
`,
);
console.log(`wrote ${outFile}`);
