/**
 * Generate src/lib/brandIcons.generated.ts from @lobehub/icons-static-svg.
 *
 * The monochrome variants are the ones worth shipping: they paint with
 * `fill="currentColor"`, so inlined into the page they take the surrounding
 * text colour and stay legible in both themes. The colour variants cannot do
 * that — several of them (Kimi among them) draw their glyph in white for use on
 * a branded tile, which disappears on a light page — and `currentColor` does
 * not resolve at all inside an <img>, because the image is a separate document.
 *
 * Run with: bun scripts/generate-brand-icons.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const iconsDir = join(
  dirname(require.resolve("@lobehub/icons-static-svg/package.json")),
  "icons"
);
const outFile = join(here, "../src/lib/brandIcons.generated.ts");

/** Every slug `modelIcons.ts` can return, plus the platform marks. */
const SLUGS = [
  "antgroup", "arcee", "aws", "azure", "baidu", "bedrock", "bytedance",
  "claude", "cloudflare", "cursor", "deepseek", "doubao", "fireworks",
  "gemini", "gemma", "grok", "hunyuan", "kimi", "longcat", "meta", "minimax",
  "mistral", "nousresearch", "nvidia", "ollama", "openai", "openrouter",
  "perplexity", "qwen", "stepfun", "volcengine", "wenxin", "windsurf",
  "xiaomimimo", "zai",
  // Platforms, used by the docs install tabs.
  "apple", "microsoft",
] as const;

/** Pull the drawable children out of the <svg> wrapper. */
function innerMarkup(svg: string): string {
  const open = svg.indexOf(">", svg.indexOf("<svg"));
  const close = svg.lastIndexOf("</svg>");
  return svg
    .slice(open + 1, close)
    .replace(/<title>.*?<\/title>/gs, "")
    .replace(/\s+/g, " ")
    .trim();
}

const entries: string[] = [];
const missing: string[] = [];

for (const slug of SLUGS) {
  try {
    const svg = readFileSync(join(iconsDir, `${slug}.svg`), "utf8");
    // The source declares fill="currentColor" on the <svg> root and lets the
    // paths inherit; callers must re-apply it on their own wrapper.
    if (!svg.includes("currentColor")) {
      // A mark that hardcodes its colours cannot follow the theme; better to
      // know at build time than to ship an invisible icon.
      console.warn(`warn: ${slug}.svg does not use currentColor`);
    }
    entries.push(
      `  ${JSON.stringify(slug)}: ${JSON.stringify(innerMarkup(svg))},`
    );
  } catch {
    missing.push(slug);
  }
}

if (missing.length > 0) {
  console.error(`missing icons: ${missing.join(", ")}`);
  process.exit(1);
}

const file = `// Generated by scripts/generate-brand-icons.ts — do not edit.
//
// Inlined monochrome brand marks from @lobehub/icons-static-svg. They paint
// with currentColor, so they inherit the surrounding text colour and stay
// legible in both themes.

export const BRAND_ICON_PATHS: Record<string, string> = {
${entries.join("\n")}
};
`;

writeFileSync(outFile, file);
console.log(`wrote ${entries.length} icons to ${outFile}`);
