//! Command Code transcripts produced by the released writers themselves.
//!
//! The fixtures under `tests/fixtures/commandcode/` were generated by running
//! the session writers extracted from the published `command-code` npm
//! bundles (provenance and hashes in that directory's README). They pin how
//! each transcript schema is read, and in particular that a v3 `usage` block
//! is counted once: `inputTokens` is the AI SDK's whole-prompt total, so the
//! cache buckets are parts of it rather than additions to it.
//!
//! Fixtures contributed by @geminixiang in missuo/tokens#67.

use std::fs;
use std::path::{Path, PathBuf};

use tempfile::TempDir;
use tokens_core::sessions::commandcode::parse_commandcode_file;
use tokens_core::CostSource;

const V3_WRITERS: &[&str] = &["1.0.0", "1.20.0", "1.50.0", "1.52.0", "1.53.0"];
const LEGACY_WRITERS: &[&str] = &["0.17.18", "0.50.0", "0.52.5"];

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/commandcode")
        .join(format!("{name}.jsonl"))
}

/// Lay a fixture out the way Command Code does on disk, next to a
/// `config.json` naming the agent model the legacy schema falls back to.
fn install(dir: &TempDir, name: &str) -> PathBuf {
    let root = dir.path().join(".commandcode");
    let project = root.join("projects").join("synthetic-project");
    fs::create_dir_all(&project).unwrap();
    fs::write(
        root.join("config.json"),
        r#"{"provider":"anthropic","model":"claude-sonnet-4-6"}"#,
    )
    .unwrap();
    let target = project.join(format!("{name}.jsonl"));
    fs::copy(fixture(name), &target).unwrap();
    target
}

#[test]
fn v3_usage_counts_each_prompt_token_once() {
    for writer in V3_WRITERS {
        let dir = TempDir::new().unwrap();
        let messages = parse_commandcode_file(&install(&dir, writer));

        let reported: Vec<_> = messages
            .iter()
            .filter(|message| message.cost_source == CostSource::ProviderReported)
            .collect();
        assert_eq!(reported.len(), 2, "{writer}: two usage-bearing replies");

        for message in reported {
            // usage: inputTokens 2000 (whole prompt), cacheRead 700,
            // cacheWrite 200 (cacheWriteTokens1h is a subset, not a bucket).
            assert_eq!(message.tokens.input, 1100, "{writer}: uncached remainder");
            assert_eq!(message.tokens.cache_read, 700, "{writer}");
            assert_eq!(message.tokens.cache_write, 200, "{writer}");
            assert_eq!(message.tokens.output, 50, "{writer}");
            assert_eq!(message.tokens.total(), 2050, "{writer}: 2000 prompt + 50 output");
        }
    }
}

#[test]
fn v3_embedded_costs_are_preserved_including_zero() {
    for writer in V3_WRITERS {
        let dir = TempDir::new().unwrap();
        let messages = parse_commandcode_file(&install(&dir, writer));
        let mut costs: Vec<f64> = messages
            .iter()
            .filter(|message| message.cost_source == CostSource::ProviderReported)
            .map(|message| message.cost)
            .collect();
        costs.sort_by(|a, b| a.partial_cmp(b).unwrap());
        assert_eq!(costs, vec![0.0, 0.25], "{writer}");
    }
}

#[test]
fn legacy_schemas_still_parse() {
    for writer in LEGACY_WRITERS {
        let dir = TempDir::new().unwrap();
        let messages = parse_commandcode_file(&install(&dir, writer));
        assert!(!messages.is_empty(), "{writer}: legacy transcript produced nothing");
        assert!(
            messages.iter().all(|message| message.tokens.total() > 0),
            "{writer}: legacy turns are estimated from text"
        );
    }
}
